version: '3.7'

services:

  cockroach-node-1:
    image: cockroachdb/cockroach
    container_name: cockroach-node-1
    command: start --insecure --advertise-addr=cockroach-node-1 --join=cockroach-node-1
    volumes:
      - cockroach-node-1:/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - app-network

  cockroach-node-2:
    image: cockroachdb/cockroach
    container_name: cockroach-node-2
    command: start --insecure --advertise-addr=cockroach-node-2 --join=cockroach-node-1:26257
    volumes:
      - cockroach-node-2:/cockroach-data
    networks:
      - app-network

  init:
    image: cockroachdb/cockroach
    container_name: cockroach-cluster-init
    command: init --insecure --host=cockroach-node-1
    depends_on:
      - cockroach-node-1
    networks:
      - app-network

  app:
    container_name: twitter-feed
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - cockroach-node-1
      - cockroach-node-2
      # - kafka
    networks:
      - app-network

volumes:
  cockroach-node-1:
  cockroach-node-2:

networks:
  app-network:
    driver: bridge