version: '3.7'

services:
  cockroach-node-1:
    image: cockroachdb/cockroach
    container_name: cockroach-node-1
    command: start --insecure --advertise-addr=cockroach-node-1 --join=cockroach-node-1
    volumes:
      - cockroach-node-1:/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    networks:
      - app-network

  cockroach-node-2:
    image: cockroachdb/cockroach
    container_name: cockroach-node-2
    command: start --insecure --advertise-addr=cockroach-node-2 --join=cockroach-node-1:26257
    volumes:
      - cockroach-node-2:/cockroach-data
    networks:
      - app-network

  init:
    image: cockroachdb/cockroach
    container_name: cockroach-cluster-init
    command: init --insecure --host=cockroach-node-1
    depends_on:
      - cockroach-node-1
    networks:
      - app-network

  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-network

  control-center:
    container_name: kafka-control-center
    image: confluentinc/cp-enterprise-control-center:latest
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    networks:
     - app-network

  app:
    container_name: twitter-feed
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.example
    ports:
      - 5000:5000
    depends_on:
      - cockroach-node-1
      - cockroach-node-2
      - kafka
    networks:
      - app-network

volumes:
  cockroach-node-1:
  cockroach-node-2:

networks:
  app-network:
    driver: bridge
